<?php

namespace AppBundle\Repository;

/**
 * BcclientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcclientRepository extends \Doctrine\ORM\EntityRepository
{
}
