<?php

namespace AppBundle\Repository;

/**
 * BcfournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcfournisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
