<?php

namespace AppBundle\Repository;

/**
 * CompteBancaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteBancaireRepository extends \Doctrine\ORM\EntityRepository
{
}
