<?php

namespace AppBundle\Repository;

/**
 * DetailvirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailvirementRepository extends \Doctrine\ORM\EntityRepository
{
}
