<?php

namespace AppBundle\Repository;

/**
 * FactureHsupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureHsupRepository extends \Doctrine\ORM\EntityRepository
{
}
