<?php

namespace AppBundle\Repository;

/**
 * FacturefournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturefournisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
