<?php

namespace AppBundle\Repository;

/**
 * LigneFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFactureRepository extends \Doctrine\ORM\EntityRepository
{
}
