<?php

namespace AppBundle\Repository;

/**
 * ParametrageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametrageRepository extends \Doctrine\ORM\EntityRepository
{
}
