<?php

namespace AppBundle\Repository;

/**
 * ProjetconsultantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetconsultantRepository extends \Doctrine\ORM\EntityRepository
{
}
