<?php

namespace AppBundle\Repository;

/**
 * VirementfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VirementfRepository extends \Doctrine\ORM\EntityRepository
{
}
